name: Build and Deploy

on:
  push:
    branches:
      - master  # 修改为你的默认分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install
          npm install -g vuepress@next  # 安装 VitePress

      - name: Build
        run: npm run build  # 执行 VitePress 构建命令

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PATH_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          publish_branch: gh-pages # 推送到关联仓库的 gh-pages 分支
          dotfiles: true  # 包括在提交中，即使被 .gitignore 文件忽略
